import { Inter } from 'next/font/google'
import './globals.css'
import DrawerAppBar from './navBar/navBar'
import Foot from './footer/foot'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DrawerAppBar />
        {children}
        <Foot />
      </body>
    </html>
  )
}
